namespace AutoPartsERP.Infrastructure.Persistence.EntityConfigurations;

public sealed class ApprovalDecisionConfiguration : IEntityTypeConfiguration<ApprovalDecision>
{
    public void Configure(EntityTypeBuilder<ApprovalDecision> builder)
    {
        builder.ToTable("approval_decisions");
        builder.HasKey(x => x.Id);
        // Ids are generated by the domain (Guid.NewGuid()). Without this EF treats a new child discovered through a
        // tracked navigation as already existing (UPDATE) and SaveChanges throws DbUpdateConcurrencyException.
        builder.Property(x => x.Id).ValueGeneratedNever();
        builder.Property(x => x.Status).HasMaxLength(20).IsRequired();
        builder.Property(x => x.Comment).HasColumnType("text");
        builder.Property(x => x.ReviewedAtUtc).HasColumnType("timestamp with time zone").IsRequired();
        builder.Property(x => x.CreatedAtUtc).HasColumnType("timestamp with time zone").IsRequired();
        builder.Property(x => x.UpdatedAtUtc).HasColumnType("timestamp with time zone");
    }
}
