namespace AutoPartsERP.Contracts.Invoices;

public sealed record InvoiceLineDto(
    Guid Id,
    int LineNumber,
    Guid SkuId,
    string SkuCode,
    string SkuName,
    Guid? BatchId,
    Guid LocationId,
    decimal Quantity,
    decimal UnitPriceSyp,
    decimal UnitPriceUsd,
    decimal DiscountPct,
    decimal LineTotalSyp,
    decimal LineTotalUsd,
    decimal GrossMarginSyp,
    decimal GrossMarginUsd,
    decimal GrossMarginPct,
    bool IsPriceOverride,
    string? OverrideReason);

public sealed record InvoiceListItemDto(
    Guid Id,
    string InvoiceNumber,
    string Status,
    string Type,
    Guid CustomerId,
    string CustomerName,
    DateOnly InvoiceDate,
    DateOnly DueDate,
    decimal TotalSyp,
    decimal TotalUsd,
    decimal BalanceSyp,
    decimal BalanceUsd,
    string StatusDisplay,
    string TypeDisplay,
    string DueDateDisplay);

public sealed record InvoiceDto(
    Guid Id,
    string InvoiceNumber,
    string Status,
    string Type,
    Guid CustomerId,
    string CustomerCode,
    string CustomerName,
    DateOnly InvoiceDate,
    DateOnly DueDate,
    decimal TotalSyp,
    decimal TotalUsd,
    decimal PaidSyp,
    decimal PaidUsd,
    decimal BalanceSyp,
    decimal BalanceUsd,
    string StatusDisplay,
    string TypeDisplay,
    string DueDateDisplay,
    string TotalSypInWords,
    string TotalUsdInWords,
    IReadOnlyCollection<InvoiceLineDto> Lines);
