using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace AutoPartsERP.Infrastructure.Persistence.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("20240101000000_CreateIdentitySchema")]
public sealed class CreateIdentitySchema : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\";");
        migrationBuilder.Sql("CREATE EXTENSION IF NOT EXISTS \"ltree\";");
        migrationBuilder.Sql("CREATE EXTENSION IF NOT EXISTS \"pg_trgm\";");

        migrationBuilder.Sql("""
            CREATE TABLE IF NOT EXISTS asp_net_roles (
                id uuid PRIMARY KEY,
                name varchar(256) NULL,
                normalized_name varchar(256) NULL,
                concurrency_stamp text NULL,
                is_system boolean NOT NULL DEFAULT false,
                description text NULL,
                created_at timestamptz NOT NULL DEFAULT now(),
                created_by uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000'
            );

            CREATE TABLE IF NOT EXISTS asp_net_users (
                id uuid PRIMARY KEY,
                user_name varchar(256) NULL,
                normalized_user_name varchar(256) NULL,
                email varchar(256) NULL,
                normalized_email varchar(256) NULL,
                email_confirmed boolean NOT NULL,
                password_hash text NULL,
                security_stamp text NULL,
                concurrency_stamp text NULL,
                phone_number text NULL,
                phone_number_confirmed boolean NOT NULL,
                two_factor_enabled boolean NOT NULL,
                lockout_end timestamptz NULL,
                lockout_enabled boolean NOT NULL,
                access_failed_count integer NOT NULL,
                full_name varchar(200) NOT NULL DEFAULT '',
                last_login_at timestamptz NULL,
                created_at timestamptz NOT NULL DEFAULT now(),
                created_by uuid NULL
            );

            CREATE TABLE IF NOT EXISTS asp_net_role_claims (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                role_id uuid NOT NULL REFERENCES asp_net_roles(id) ON DELETE CASCADE,
                claim_type text NULL,
                claim_value text NULL
            );

            CREATE TABLE IF NOT EXISTS asp_net_user_claims (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id uuid NOT NULL REFERENCES asp_net_users(id) ON DELETE CASCADE,
                claim_type text NULL,
                claim_value text NULL
            );

            CREATE TABLE IF NOT EXISTS asp_net_user_logins (
                login_provider text NOT NULL,
                provider_key text NOT NULL,
                provider_display_name text NULL,
                user_id uuid NOT NULL REFERENCES asp_net_users(id) ON DELETE CASCADE,
                PRIMARY KEY (login_provider, provider_key)
            );

            CREATE TABLE IF NOT EXISTS asp_net_user_roles (
                user_id uuid NOT NULL REFERENCES asp_net_users(id) ON DELETE CASCADE,
                role_id uuid NOT NULL REFERENCES asp_net_roles(id) ON DELETE CASCADE,
                assigned_at timestamptz NOT NULL DEFAULT now(),
                assigned_by uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000',
                expires_at timestamptz NULL,
                PRIMARY KEY (user_id, role_id)
            );

            CREATE TABLE IF NOT EXISTS asp_net_user_tokens (
                user_id uuid NOT NULL REFERENCES asp_net_users(id) ON DELETE CASCADE,
                login_provider text NOT NULL,
                name text NOT NULL,
                value text NULL,
                PRIMARY KEY (user_id, login_provider, name)
            );
            """);

        migrationBuilder.Sql("""
            CREATE UNIQUE INDEX IF NOT EXISTS ix_asp_net_roles_normalized_name
                ON asp_net_roles(normalized_name);
            CREATE INDEX IF NOT EXISTS ix_asp_net_users_normalized_email
                ON asp_net_users(normalized_email);
            CREATE UNIQUE INDEX IF NOT EXISTS ix_asp_net_users_normalized_user_name
                ON asp_net_users(normalized_user_name);
            CREATE INDEX IF NOT EXISTS ix_asp_net_role_claims_role_id
                ON asp_net_role_claims(role_id);
            CREATE INDEX IF NOT EXISTS ix_asp_net_user_claims_user_id
                ON asp_net_user_claims(user_id);
            CREATE INDEX IF NOT EXISTS ix_asp_net_user_logins_user_id
                ON asp_net_user_logins(user_id);
            CREATE INDEX IF NOT EXISTS ix_asp_net_user_roles_role_id
                ON asp_net_user_roles(role_id);
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
    }
}
